### ISSUE TITLE
Move issue labels into a config file

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner-Issue-Collector#1]
Currently the demo app defaults to using hard-coded issue labels, at ~line 65 in of findIssues.js. These default values are set to ['hacktoberfest', 'good+first+issue']

These issues should be pulled either into a issueLabels.json file that lives in the InputFiles directory, or something similar, to make it easier for people to customize this to their own contexts.

**Comment by TheSeally** [comment]
Hello. Can I try to fix this issue?

**Comment by DuaneOBrien** [comment]
Go for it!

**Comment by TheSeally** [comment]
Can you add a "hacktoberfest" tag to this repo, please? I take part in hacktoberfest 2020 and this is a requirement for PR this year
If not there is no problem, I will fix it anyway

**Comment by DuaneOBrien** [comment]
Done. I've marked this issue as Claimed and assigned it to TheSeally
