### ISSUE TITLE
Write utility script to parse and transform despcloud output

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner-Issue-Collector#11]
Deps.cloud is an open source tool that helps you understand your dependencies. There is a tool called `identify-contribution-candidates` in the [depscloud/hacktoberfest](https://github.com/depscloud/hacktoberfest) repo that can be used to generate a list of contribution candidates - projects with source repositories that which you can check for available issues. The output of `identify-contribution-candidates` is a candidate.json file that looks like this:

```
[
  {
    "repository_url": "https://github.com/indeedeng/k8dash",
    "score": 25
  },
  {
    "repository_url": "https://github.com/fasterxml/jackson",
    "score": 20
  },
  {
    "repository_url": "https://github.com/indeedeng/starfish",
    "score": 15
  },
  {
    "repository_url": "https://github.com/depscloud/depscloud",
    "score": 10
  },
  {
    "repository_url": "https://github.com/indeedeng/mariner",
    "score": 5
  }
]
```

It would be great to have a utility that reads in a candidates.json file as generated by `identify-contribution-candidates` and transforms it into the inputData.json format that Mariner expects:

```
{
    "indeedeng/k8dash": 25,
    "fasterxml/jackson": 20,
    "indeedeng/starfish": 15,
    "depscloud/depscloud": 10,
    "indeedeng/mariner": 5
}
```

When building this utility, note that the repository_url field that depscloud generates will not always contain a github.com url (they may be bitbucket or other locations) and they will not always start with https (some are http, and some may start with something like scm:git:ssh://git@bitbucket.org). The utility will need to account for these variations.

A list of variations I've seen in repository_url field that might also trip things up:

```
"repository_url": "http://svn.apache.org/something"
"repository_url": "https://github.com/OWNER/REPO/something"
"repository_url": "https://github.com/OWNER/REPO/something/something"
"repository_url": "scm:git:git://github.com/OWNER/REPO.git/something"
```  

As part of completing this issue, please do the following:

- Use the Utilities/generateGitHubMarkdown.js file as a guide for how to handle reading in and writing out files
- Include a Tests/candidate.json file that includes some candidates that should be filtered out by the script, and will generate the existing file at InputFiles/inputData.json

**Comment by Nebrethar** [comment]
I will take this one on today. Thanks for the extra context

**Comment by Nebrethar** [comment]
The code is on [my fork](https://github.com/Nebrethar/Mariner-Issue-Collector) and it seems to work for the cases I've tested 😁

I'm not sure of the structure you'd like so I'm holding off from a pull request. The way I thought about it, the deps converter (for now) is a separate file from the issue collector. It's also got the "DepsCloud" folder for inputs and outputs to allow potential batch conversions in the future.

Let me know if you have any other questions or comments, or if you think it's appropriate to go ahead with the PR as-is.

**Comment by Nebrethar** [comment]
Side Note: I deployed deps.cloud with docker and the format is not the same for different outputs, though it seems easier to work with. Do you want to eventually provide support for other schemas?

**Comment by DuaneOBrien** [comment]
I think you're thinking about the converter the way I have been- a little unix-y. For context, the previous internal version of Mariner was a collection of discrete scripts that each only did one thing. So I prefer the approach that has discrete utilities that do their own thing, even though it's less efficient. But that's a personal preference.

Re: the fork. I was being a little lazy in my thinking about tests when I wrote them into the issue above. Specifically, I think setting the expectation that all tests use the InputFiles/inputData.json file as their expected output was naive of me. Let's move the DepsCloud folder into a Tests folder, and that will allow us to keep things a little tidy. 

Feel free to start a draft pull request, we can handle anything else from there.

**Comment by DuaneOBrien** [comment]
I forgot to comment re: the other deps.cloud format and outputs. 

I'm not clear on what the difference is between the format used by the `identify-contribution-candidates` utility and from deps.cloud proper. For now, I think it's fine to scope this PR to just supporting the utility, and we can pick up supporting other depscloud formats down the line. Or they may converge.

**Comment by Nebrethar** [comment]
Thanks for the help with this. I look forward to working on it this coming Monday 😁

I've got it pretty close to standalone already! My question, also for clarity:
What is your idea of the workflow? 

For example, if I get what you are saying..
1. User navigates to the Utilities folder
2. User runs:
```
  $ node convertFromDepsCloud.js ./path/to/inptufile.json
```
3. File is converted and put in an output folder

**Comment by DuaneOBrien** [comment]
Utilities/generateGitHubMarkdown.js assumes filenames that would be in OutputFiles/ but allows overloading them with environment variables. If we followed that pattern, we'd end up in this case with something like:

`MARINER_DEPSCLOUD_INPUT=./path/to/file node convertFromDepsCloud,js`

Which feels un-node-like but is at least consistent?

**Comment by DuaneOBrien** [comment]
Adding some newly found repository_url formats that deps.cloud may return:

```
"repository_url": "http://some.otherurl.com"
"repository_url": "http://some.otherurl.com/"
"repository_url": "http://git.someurl.com/somerepo.git"
"repository_url": "https://github.com/someorganization"

```
