### ISSUE TITLE
Update the readme to close documentation gaps.

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner-Issue-Collector#2]
The README currently does not contain any documentation that describes the following:

* How to change the default set of issue labels
* How repo weights are used to sort results 
* How the GitHub pagination and querying behaves
* How to use the demo app in a private repo
* How the MARINER_MAX_ISSUES_AGE environment variable is used and what it does

**Comment by DuaneOBrien** [comment]
Adding some overall improvements to the readme would be an easy contribution. For the purpose of Hacktoberfest, a PR will be accepted for this issue only if it addresses the known documentation gaps listed above.

**Comment by ShraddhaGeek** [comment]
@DuaneOBrien  Can you please assign this to me

**Comment by DuaneOBrien** [comment]
@ShraddhaGeek done!

**Comment by DuaneOBrien** [comment]
I'm moving this one back to unassaigned. @ShraddhaGeek if you'd still like to work on this issue, please let us know and we'd be happy to reassign.

**Comment by jennvance** [comment]
Hi there, I'd like to work on this issue. Can you assign me?

**Comment by DuaneOBrien** [comment]
Done!

**Comment by jennvance** [comment]
Created new pull request for this issue #26 

Let me know if you see anything that can be improved.

**Comment by DuaneOBrien** [comment]
Thanks @jennvance ! I added some comments to the PR that I think will improve the language a bit.

**Comment by jennvance** [comment]
@DuaneOBrien Thank you. I'll see what I can do.

**Comment by DuaneOBrien** [comment]
Fixed by #26
