### ISSUE TITLE
Action exits with an error if no new issues are going.

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner-Issue-Collector#3]
The Commit and Push step of the GitHub Action exits with an error if no files have changed. This makes it look like the action didn't run successfully.

**Comment by DuaneOBrien** [comment]
An easy fix for this would be to set the action to run once a day rather than every 8 hours. This would result in a new githubMarkdown.md file every day.

An alternative would be to add the run time to the top of the githubMarkdown.md file, which would ensure it's different every time.

**Comment by Nebrethar** [comment]
I poked around at this issue and tried two solutions that I **thought** would work.
I trued solutions for `continue-on-error` and `if: always()` and neither of them were successful on my fork. I think the addition of the runtime is the best idea because I can't find anything that will suppress that failure check.

**Comment by DuaneOBrien** [comment]
I think the addition of runtime also helps the end user. Adding it as a top level header on the markdown sends a clear signal to the user about how fresh the data is. 

It's a silly fix, IMO, but it solves the problem.

**Comment by jakegut** [comment]
> I think the addition of runtime also helps the end user. Adding it as a top level header on the markdown sends a clear signal to the user about how fresh the data is.

Can I try to implement this?

Also, I'm assuming that `findIssues.js` and the github MD generator run at the same time (right after each other)?

**Comment by DuaneOBrien** [comment]
@jakeryang go for it!

You're correct about the run order, you'll find it spelled out in the .github/workflows/main.yml file
