### ISSUE TITLE
Upgrade to use luxon instead of moment

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/Mariner-Issue-Collector#31]
Moment.js is in a deprecated state. This project needs to be updated to use [luxon](https://moment.github.io/luxon/) instead.

At this time, moment appears to be used in:
* findIssues.js
* Utilities/generateHtml.js
* Utilities/generateGitHubMarkdown.js
* Utilities/generateConfluenceMarkdown.js

**Comment by Gurvir-Sandhar** [comment]
can I work on this issue?

**Comment by ozgunbal** [comment]
sorry @Gurvir-Sandhar , I already started to this issue without notify at first.

**Comment by Gurvir-Sandhar** [comment]
@ozgunbal No worries.
